export { default as StarsBackground } from './stars-background.vue'
export { default as Button } from './button.vue'
export { default as Input } from './input.vue'
export { default as Modal } from './modal.vue'
export { default as RainbowBlock } from './rainbow-block.vue'
